FROM zhongruizhi/spark-maven-template:3.5.1-hadoop3.3.6-amd64

LABEL MAINTAINER="Ruizhi Zhong <ruizhi.zhong@outlook.com>"

ENV SPARK_APPLICATION_JAR_NAME Docker-Maven-Template-0.1.0-SNAPSHOT
ENV SPARK_APPLICATION_MAIN_CLASS eu.bde.template.maven.WordCount
ENV SPARK_APPLICATION_ARGS "/spark/README.md"